'use server'

import { createClient } from '@/lib/supabase/server'
import { createServiceClient } from '@/lib/supabase/service'

const UUID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

export type CreateInviteResult =
  | { ok: true; token: string }
  | { ok: false; error: string }

/**
 * Creates a pending parent invite for a student and returns the raw token.
 *
 * The insert runs through the service-role client because parent_student_links
 * has zero RLS policies, so the authorization check below is the ONLY thing
 * standing between a caller and any student in the database. Do not relax it.
 */
export async function createParentInvite(
  studentId: string
): Promise<CreateInviteResult> {
  if (!UUID_PATTERN.test(studentId.trim())) {
    return { ok: false, error: 'That does not look like a valid student ID.' }
  }

  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()

  if (!user) {
    return { ok: false, error: 'You must be signed in to create an invite.' }
  }

  const service = createServiceClient()

  const { data: profile, error: profileError } = await service
    .from('profiles')
    .select('id, role, school_id')
    .eq('id', user.id)
    .maybeSingle()

  if (profileError || !profile) {
    return { ok: false, error: 'Could not load your profile.' }
  }

  const { data: student, error: studentError } = await service
    .from('students')
    .select('id, school_id, profile_id')
    .eq('id', studentId.trim())
    .maybeSingle()

  if (studentError || !student) {
    return { ok: false, error: 'No student found with that ID.' }
  }

  // Mirrors the RLS rules in migrations 002/003, enforced in code because the
  // service-role client bypasses them.
  const isSystemAdmin = profile.role === 'system_admin'
  const isSchoolAdminHere =
    profile.role === 'school_admin' && profile.school_id === student.school_id
  const isThisStudent =
    profile.role === 'student' && student.profile_id === user.id

  if (!isSystemAdmin && !isSchoolAdminHere && !isThisStudent) {
    return {
      ok: false,
      error: 'You do not have permission to invite a parent for this student.',
    }
  }

  const { data: link, error: insertError } = await service
    .from('parent_student_links')
    .insert({
      student_id: student.id,
      invited_by: profile.id,
      status: 'pending',
      // invite_token is generated by the column default.
    })
    .select('invite_token')
    .single()

  if (insertError || !link) {
    return { ok: false, error: 'Could not create the invite. Please try again.' }
  }

  return { ok: true, token: link.invite_token }
}
